
package Telas;

import BLL.FuncionariosBLL;
import DTO.FuncionariosDTO;
import static Telas.Cadastro_Funcionarios.tb_funcoionario;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Alterar_Funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form Alterar_Funcionarios
     */
    public Alterar_Funcionarios() {
        initComponents();
    }
    public void preencherTabela(){
        
        tb_funcoionario.getColumnModel().getColumn(0).setPreferredWidth(50);
        tb_funcoionario.getColumnModel().getColumn(0).setMaxWidth(50);
        tb_funcoionario.getColumnModel().getColumn(0).setMinWidth(50);
       
        tb_funcoionario.getColumnModel().getColumn(1).setPreferredWidth(300);
        tb_funcoionario.getColumnModel().getColumn(1).setMaxWidth(300);
        tb_funcoionario.getColumnModel().getColumn(1).setMinWidth(300);
        
        tb_funcoionario.getColumnModel().getColumn(2).setPreferredWidth(150);
        tb_funcoionario.getColumnModel().getColumn(2).setMaxWidth(150);
        tb_funcoionario.getColumnModel().getColumn(2).setMinWidth(150);
        
        tb_funcoionario.getColumnModel().getColumn(3).setPreferredWidth(120);
        tb_funcoionario.getColumnModel().getColumn(3).setMaxWidth(120);
        tb_funcoionario.getColumnModel().getColumn(3).setMinWidth(120);
       
        tb_funcoionario.getColumnModel().getColumn(4).setPreferredWidth(200);
        tb_funcoionario.getColumnModel().getColumn(4).setMaxWidth(200);
        tb_funcoionario.getColumnModel().getColumn(4).setMinWidth(200);
        
        tb_funcoionario.getColumnModel().getColumn(5).setPreferredWidth(100);
        tb_funcoionario.getColumnModel().getColumn(5).setMaxWidth(100);
        tb_funcoionario.getColumnModel().getColumn(5).setMinWidth(100);
        
        tb_funcoionario.getColumnModel().getColumn(6).setPreferredWidth(100);
        tb_funcoionario.getColumnModel().getColumn(6).setMaxWidth(100);
        tb_funcoionario.getColumnModel().getColumn(6).setMinWidth(100);
        
        tb_funcoionario.getColumnModel().getColumn(7).setPreferredWidth(100);
        tb_funcoionario.getColumnModel().getColumn(7).setMaxWidth(100);
        tb_funcoionario.getColumnModel().getColumn(7).setMinWidth(100);
        
        tb_funcoionario.getColumnModel().getColumn(8).setPreferredWidth(50);
        tb_funcoionario.getColumnModel().getColumn(8).setMaxWidth(50);
        tb_funcoionario.getColumnModel().getColumn(8).setMinWidth(50);
        
        tb_funcoionario.getColumnModel().getColumn(9).setPreferredWidth(100);
        tb_funcoionario.getColumnModel().getColumn(9).setMaxWidth(100);
        tb_funcoionario.getColumnModel().getColumn(9).setMinWidth(100);
        
        FuncionariosBLL rg = new FuncionariosBLL();
        tb_funcoionario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel modelo = (DefaultTableModel) tb_funcoionario.getModel();
        modelo.setNumRows(0);
        
        for(FuncionariosDTO fdto:rg.listarFuncionario()){
         modelo.addRow(new Object[]{
                fdto.getId_funcionario(),
                fdto.getNome(),
                fdto.getCpf(),
                fdto.getIdentidade(),
                fdto.getEndereco(),
                fdto.getCep(),
                fdto.getNumero(),
                fdto.getCidade(),
                fdto.getUf(),
                fdto.getTelefone()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_identidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_endereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cep = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_uf = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JFormattedTextField();
        btn_cadastar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(695, 415));

        jLabel1.setText("Código");

        txt_cod.setEnabled(false);

        jLabel2.setText("Nome");

        jLabel3.setText("Cpf");

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Indentidade");

        jLabel5.setText("Endereço");

        jLabel6.setText("Cep");

        try {
            txt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("Numero");

        jLabel8.setText("Cidade");

        jLabel9.setText("UF");

        txt_uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabel10.setText("Telefone");

        try {
            txt_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btn_cadastar.setText("Alterar");
        btn_cadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cadastar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_endereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nome, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel5))
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_cep, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_cpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(txt_identidade, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(txt_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(txt_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_identidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_cadastar)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastarActionPerformed
        FuncionariosBLL rg = new FuncionariosBLL();
        FuncionariosDTO funcionariosDTO = new FuncionariosDTO();
        if(!txt_nome.getText().equals("")&&
            !txt_cpf.getText().equals("")&&
            !txt_endereco.getText().equals("") &&
            !txt_cep.getText().equals("") &&
            !txt_cidade.getText().equals("") &&
            !txt_uf.getSelectedItem().equals("-") &&
            !txt_telefone.getText().equals("")
                ){
                funcionariosDTO.setId_funcionario(Integer.parseInt(txt_cod.getText()));
                funcionariosDTO.setNome(txt_nome.getText());
                funcionariosDTO.setCpf(txt_cpf.getText());
                funcionariosDTO.setIdentidade(txt_identidade.getText());
                funcionariosDTO.setEndereco(txt_endereco.getText());
                funcionariosDTO.setCep(txt_cep.getText());
                funcionariosDTO.setNumero(Integer.parseInt(txt_numero.getText()));
                funcionariosDTO.setCidade(txt_cidade.getText());
                funcionariosDTO.setUf(txt_uf.getSelectedItem().toString());
                funcionariosDTO.setTelefone(txt_telefone.getText());
     
                rg.alterar(funcionariosDTO);
                JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
                preencherTabela();
                this.dispose();          
        }else{       
            JOptionPane.showMessageDialog(null, "Campos vazios!");                
        }
    }//GEN-LAST:event_btn_cadastarActionPerformed

    /**
     * @param args the command line arguments
     */  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar_Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alterar_Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JFormattedTextField txt_cep;
    public static javax.swing.JTextField txt_cidade;
    public static javax.swing.JTextField txt_cod;
    public static javax.swing.JFormattedTextField txt_cpf;
    public static javax.swing.JTextField txt_endereco;
    public static javax.swing.JTextField txt_identidade;
    public static javax.swing.JTextField txt_nome;
    public static javax.swing.JTextField txt_numero;
    public static javax.swing.JFormattedTextField txt_telefone;
    public static javax.swing.JComboBox<String> txt_uf;
    // End of variables declaration//GEN-END:variables

}
