/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import BLL.ProdutosBLL;
import DTO.ProdutosDTO;
import static Telas.Cadastro_Produtos.tb_produtos;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Alterar_Produtos extends javax.swing.JFrame {

    /**
     * Creates new form Alterar_Produtos
     */
    public Alterar_Produtos() {
        initComponents();
    }
    public void preencherTabela(){
        
        tb_produtos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tb_produtos.getColumnModel().getColumn(0).setMaxWidth(50);
        tb_produtos.getColumnModel().getColumn(0).setMinWidth(50);
        
        tb_produtos.getColumnModel().getColumn(1).setPreferredWidth(300);
        tb_produtos.getColumnModel().getColumn(1).setMaxWidth(300);
        tb_produtos.getColumnModel().getColumn(1).setMinWidth(300);
        
        tb_produtos.getColumnModel().getColumn(2).setPreferredWidth(200);
        tb_produtos.getColumnModel().getColumn(2).setMaxWidth(200);
        tb_produtos.getColumnModel().getColumn(2).setMinWidth(200);
        
        tb_produtos.getColumnModel().getColumn(3).setPreferredWidth(120);
        tb_produtos.getColumnModel().getColumn(3).setMaxWidth(120);
        tb_produtos.getColumnModel().getColumn(3).setMinWidth(120);
        
        tb_produtos.getColumnModel().getColumn(4).setPreferredWidth(120);
        tb_produtos.getColumnModel().getColumn(4).setMaxWidth(120);
        tb_produtos.getColumnModel().getColumn(4).setMinWidth(120);
        
        tb_produtos.getColumnModel().getColumn(5).setPreferredWidth(120);
        tb_produtos.getColumnModel().getColumn(5).setMaxWidth(120);
        tb_produtos.getColumnModel().getColumn(5).setMinWidth(120);
        
        tb_produtos.getColumnModel().getColumn(6).setPreferredWidth(120);
        tb_produtos.getColumnModel().getColumn(6).setMaxWidth(120);
        tb_produtos.getColumnModel().getColumn(6).setMinWidth(120);
        
        tb_produtos.getColumnModel().getColumn(7).setPreferredWidth(120);
        tb_produtos.getColumnModel().getColumn(7).setMaxWidth(120);
        tb_produtos.getColumnModel().getColumn(7).setMinWidth(120);
        
        tb_produtos.getColumnModel().getColumn(8).setPreferredWidth(100);
        tb_produtos.getColumnModel().getColumn(8).setMaxWidth(100);
        tb_produtos.getColumnModel().getColumn(8).setMinWidth(100);
        
        ProdutosBLL rg = new ProdutosBLL();
        tb_produtos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel modelo = (DefaultTableModel) tb_produtos.getModel();
        modelo.setNumRows(0);
        
        for(ProdutosDTO pdto:rg.listarProduto()){
         modelo.addRow(new Object[]{
                pdto.getId_produto(),
                pdto.getNome(),
                pdto.getCor(),
                pdto.getQuantidade(),
                pdto.getEspessura(),              
                pdto.getAltura(),
                pdto.getLargura(),
                pdto.getComprimento(),
                pdto.getValor()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        Cor = new javax.swing.JLabel();
        txt_cor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_qntd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_espessura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_largura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_comprimento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_valor = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Código");

        txt_cod.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        Cor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Cor.setText("Cor");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Quantidade");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Espessura");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Altura");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Largura");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Comprimento");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("valor");

        btn_cadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_cadastrar.setText("Alterar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_largura, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_comprimento))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cor)
                            .addComponent(txt_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_qntd))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txt_espessura, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_cadastrar))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Cor)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qntd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_espessura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_largura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_comprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btn_cadastrar)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        ProdutosBLL rg = new ProdutosBLL();
        ProdutosDTO produtosDTO = new ProdutosDTO();
        if(!txt_nome.getText().equals("")&&
                !txt_cor.getText().equals("")&&
                !txt_qntd.getText().equals("")&&
                !txt_espessura.getText().equals("")&&
                !txt_altura.getText().equals("") &&
                !txt_largura.getText().equals("")&&
                !txt_comprimento.getText().equals("") &&
                !txt_valor.getText().equals("")
                ){
                int id = Integer.parseInt(txt_cod.getText());
                produtosDTO.setId_produto(id);
                produtosDTO.setNome(txt_nome.getText());
                produtosDTO.setCor(txt_cor.getText());
                produtosDTO.setQuantidade(Integer.parseInt(txt_qntd.getText()));
                produtosDTO.setEspessura(txt_espessura.getText());
                produtosDTO.setAltura(txt_altura.getText());
                produtosDTO.setLargura(txt_largura.getText());
                produtosDTO.setComprimento(txt_comprimento.getText());
                produtosDTO.setValor(Double.parseDouble(txt_valor.getText()));
                rg.alterar(produtosDTO);
                JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
                preencherTabela();
                this.dispose();          
        }else{       
            JOptionPane.showMessageDialog(null, "Campos vazios!");                
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alterar_Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cor;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JTextField txt_altura;
    public static javax.swing.JTextField txt_cod;
    public static javax.swing.JTextField txt_comprimento;
    public static javax.swing.JTextField txt_cor;
    public static javax.swing.JTextField txt_espessura;
    public static javax.swing.JTextField txt_largura;
    public static javax.swing.JTextField txt_nome;
    public static javax.swing.JTextField txt_qntd;
    public static javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
