/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import BLL.Login_BLL;
import DTO.Login_DTO;
import java.awt.HeadlessException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Casa
 */
public class Cadastro_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Usuario
     */
    public Cadastro_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_nivel = new javax.swing.JComboBox<>();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro de Usuários");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 180, 22);

        lbl_usuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("Usuário");
        getContentPane().add(lbl_usuario);
        lbl_usuario.setBounds(30, 110, 50, 17);

        lbl_senha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_senha.setText("Senha");
        getContentPane().add(lbl_senha);
        lbl_senha.setBounds(30, 150, 50, 17);

        txt_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txt_nome);
        txt_nome.setBounds(110, 110, 110, 30);
        getContentPane().add(txt_senha);
        txt_senha.setBounds(110, 150, 110, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 240, 190, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nível");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 190, 30, 17);

        txt_nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Administrador", "Operador" }));
        txt_nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nivelActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nivel);
        txt_nivel.setBounds(110, 190, 110, 30);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Imagens/fundoLogin.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 260, 300);

        setSize(new java.awt.Dimension(274, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login_BLL rg = new Login_BLL();
        Login_DTO login_DTO = new Login_DTO();
        String senha = String.valueOf(txt_senha.getPassword());
        if(!txt_nome.getText().equals("") && !senha.equals("") && !"-".equals(txt_nivel.getSelectedItem())){
            try {
                
                login_DTO.setNome(txt_nome.getText());
                login_DTO.setSenha(convertPasswordToMD5(txt_senha.getPassword()));
                
                login_DTO.setNivel(txt_nivel.getSelectedItem().toString().replace("Administrador", "1").replace("Operador", "2"));
                      
                try {
                    if(!rg.verificaNome(txt_nome.getText())){
                        JOptionPane.showMessageDialog(null, "Já existe usuário "+ txt_nome.getText());
                    }else{
                        rg.Inserir(login_DTO); 
                        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!"+ txt_senha.getPassword());
                        txt_nome.setText("");
                        txt_senha.setText("");
                        txt_nivel.setSelectedItem("-");
                         
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Cadastro_Usuario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Cadastro_Usuario.class.getName()).log(Level.SEVERE, null, ex);
                }
                //JOptionPane.showMessageDialog(null, txt_nome.getText()+" "+ txt_senha.getPassword()+" "+txt_nivel.getSelectedItem());
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(Cadastro_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            JOptionPane.showMessageDialog(null, "Campos vazios verifique e tente novamente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nivelActionPerformed
      
    }//GEN-LAST:event_txt_nivelActionPerformed
    public static String convertPasswordToMD5(char[] cadeia) throws NoSuchAlgorithmException {
                   String password =  new String(cadeia);
                   MessageDigest md = MessageDigest.getInstance("MD5");
                   BigInteger hash = new BigInteger(1, md.digest(password.getBytes()));
                   return String.format("%32x", hash);
               }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JComboBox<String> txt_nivel;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables
}
