/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import BLL.FuncionariosBLL;
import DTO.FuncionariosDTO;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Cadastro_Funcionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro_Funcionarios
     */
    public Cadastro_Funcionarios() {
        initComponents();
        preencherTabela();
    }
     public void preencherTabela(){
        
        this.tb_funcoionario.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.tb_funcoionario.getColumnModel().getColumn(0).setMaxWidth(50);
        this.tb_funcoionario.getColumnModel().getColumn(0).setMinWidth(50);
        
        this.tb_funcoionario.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.tb_funcoionario.getColumnModel().getColumn(1).setMaxWidth(200);
        this.tb_funcoionario.getColumnModel().getColumn(1).setMinWidth(200);
        
        this.tb_funcoionario.getColumnModel().getColumn(2).setPreferredWidth(70);
        this.tb_funcoionario.getColumnModel().getColumn(2).setMaxWidth(70);
        this.tb_funcoionario.getColumnModel().getColumn(2).setMinWidth(70);
        
        this.tb_funcoionario.getColumnModel().getColumn(3).setPreferredWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(3).setMaxWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(3).setMinWidth(150);
        
        this.tb_funcoionario.getColumnModel().getColumn(4).setPreferredWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(4).setMaxWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(4).setMinWidth(150);
        
        this.tb_funcoionario.getColumnModel().getColumn(5).setPreferredWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(5).setMaxWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(5).setMinWidth(150);
        
        this.tb_funcoionario.getColumnModel().getColumn(6).setPreferredWidth(200);
        this.tb_funcoionario.getColumnModel().getColumn(6).setMaxWidth(200);
        this.tb_funcoionario.getColumnModel().getColumn(6).setMinWidth(200);
        
        this.tb_funcoionario.getColumnModel().getColumn(7).setPreferredWidth(200);
        this.tb_funcoionario.getColumnModel().getColumn(7).setMaxWidth(200);
        this.tb_funcoionario.getColumnModel().getColumn(7).setMinWidth(200);
        
        this.tb_funcoionario.getColumnModel().getColumn(8).setPreferredWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(8).setMaxWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(8).setMinWidth(150);
        
        this.tb_funcoionario.getColumnModel().getColumn(9).setPreferredWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(9).setMaxWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(9).setMinWidth(150);
        
        this.tb_funcoionario.getColumnModel().getColumn(10).setPreferredWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(10).setMaxWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(10).setMinWidth(150);
        
        this.tb_funcoionario.getColumnModel().getColumn(11).setPreferredWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(11).setMaxWidth(150);
        this.tb_funcoionario.getColumnModel().getColumn(11).setMinWidth(150);
        
        FuncionariosBLL rg = new FuncionariosBLL();
        this.tb_funcoionario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel modelo = (DefaultTableModel) tb_funcoionario.getModel();
        modelo.setNumRows(0);
        
        for(FuncionariosDTO fdto:rg.listarFuncionario()){
         modelo.addRow(new Object[]{
                fdto.getId_funcionario(),
                fdto.getNome(),
                fdto.getCpf(),
                fdto.getIdentidade(),
                fdto.getEndereco(),
                fdto.getCep(),
                fdto.getNumero(),
                fdto.getCidade(),
                fdto.getUf(),
                fdto.getTelefone()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popuptb_funcionario = new javax.swing.JPopupMenu();
        Excluir = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_identidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_endereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_uf = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_cep = new javax.swing.JFormattedTextField();
        btn_cadastrar = new javax.swing.JButton();
        txt_telefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_funcoionario = new javax.swing.JTable();

        Excluir.setText("jMenuItem1");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        Popuptb_funcionario.add(Excluir);

        Editar.setText("jMenuItem1");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        Popuptb_funcionario.add(Editar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("aSuperArts - Manutenção de Funcionários");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Código");

        txt_cod.setEditable(false);
        txt_cod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        txt_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("CPF");

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Indentidade");

        txt_identidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Endereço");

        txt_endereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Número");

        txt_numero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Cidade");

        txt_cidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("UF");

        txt_uf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("CEP");

        try {
            txt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btn_cadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        try {
            txt_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Telefone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel3)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txt_identidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_cadastrar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel7)
                                .addGap(105, 105, 105)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(txt_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(218, 218, 218))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_identidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(btn_cadastrar)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        tb_funcoionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cpf", "Identidade", "Endereço", "Cep", "Número", "Cidade", "Uf", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_funcoionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_funcoionarioMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_funcoionarioMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_funcoionario);
        if (tb_funcoionario.getColumnModel().getColumnCount() > 0) {
            tb_funcoionario.getColumnModel().getColumn(0).setResizable(false);
            tb_funcoionario.getColumnModel().getColumn(1).setResizable(false);
            tb_funcoionario.getColumnModel().getColumn(2).setResizable(false);
            tb_funcoionario.getColumnModel().getColumn(3).setResizable(false);
            tb_funcoionario.getColumnModel().getColumn(4).setResizable(false);
            tb_funcoionario.getColumnModel().getColumn(5).setResizable(false);
            tb_funcoionario.getColumnModel().getColumn(6).setResizable(false);
            tb_funcoionario.getColumnModel().getColumn(7).setResizable(false);
            tb_funcoionario.getColumnModel().getColumn(8).setResizable(false);
            tb_funcoionario.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 329, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        FuncionariosBLL rg = new FuncionariosBLL();
        FuncionariosDTO funcionariosDTO = new FuncionariosDTO();
        
        funcionariosDTO.setNome(txt_nome.getText());
        funcionariosDTO.setCpf(txt_cpf.getText());
        funcionariosDTO.setIdentidade(txt_identidade.getText());
        funcionariosDTO.setEndereco(txt_endereco.getText());
        funcionariosDTO.setCep(txt_cep.getText());
        funcionariosDTO.setNumero(Integer.parseInt(txt_numero.getText()));
        funcionariosDTO.setCidade(txt_cidade.getText());
        funcionariosDTO.setUf(txt_uf.getSelectedItem().toString());
        funcionariosDTO.setTelefone(txt_telefone.getText());
        
        rg.inserir(funcionariosDTO);
        JOptionPane.showMessageDialog(null, "Funcionário Cadastrado" );
        preencherTabela();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void tb_funcoionarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_funcoionarioMouseReleased
        if(evt.isPopupTrigger()){
            Popuptb_funcionario.show(this, evt.getX(), 105);
            Excluir.setText("Excluir Cliente");
            Editar.setText("Editar Cliente");
            
        }
    }//GEN-LAST:event_tb_funcoionarioMouseReleased

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        FuncionariosBLL rg = new FuncionariosBLL();
        FuncionariosDTO f = new FuncionariosDTO();
        if (this.tb_funcoionario.getSelectedRowCount() > 0) {
            int linha = this.tb_funcoionario.getSelectedRow();
            f.setId_funcionario((int) this.tb_funcoionario.getValueAt(linha, 0));
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir?");
            if (resposta == JOptionPane.YES_OPTION) {
                rg.ExcluirFuncionario(f);
                preencherTabela();
                JOptionPane.showMessageDialog(null, "Excluído!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
         FuncionariosDTO funcionariosDTO = new FuncionariosDTO();
        FuncionariosBLL rg = new FuncionariosBLL();
        if (this.tb_funcoionario.getSelectedRowCount() > 0) {
            int linha = tb_funcoionario.getSelectedRow();
            funcionariosDTO.setId_funcionario((int) this.tb_funcoionario.getValueAt(linha, 0));
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(null, "Deseja mesmo editar?");
            if (resposta == JOptionPane.YES_OPTION) {
                
         Alterar_Funcionarios alterar_Funcionarios = new Alterar_Funcionarios();
         alterar_Funcionarios.setSize(700, 500);
         alterar_Funcionarios.setVisible(true);
         Alterar_Funcionarios.txt_cod.setText(tb_funcoionario.getModel().getValueAt(linha, 0).toString());
         Alterar_Funcionarios.txt_nome.setText(tb_funcoionario.getModel().getValueAt(linha, 1).toString());
         Alterar_Funcionarios.txt_cpf.setText(tb_funcoionario.getModel().getValueAt(linha, 2).toString());
         Alterar_Funcionarios.txt_identidade.setText(tb_funcoionario.getModel().getValueAt(linha, 3).toString());
         Alterar_Funcionarios.txt_endereco.setText(tb_funcoionario.getModel().getValueAt(linha, 4).toString());
         Alterar_Funcionarios.txt_cep.setText(tb_funcoionario.getModel().getValueAt(linha, 5).toString());
         Alterar_Funcionarios.txt_numero.setText(tb_funcoionario.getModel().getValueAt(linha, 6).toString());
         Alterar_Funcionarios.txt_cidade.setText(tb_funcoionario.getModel().getValueAt(linha, 7).toString());
         Alterar_Funcionarios.txt_uf.setSelectedItem(tb_funcoionario.getModel().getValueAt(linha, 8).toString());
         Alterar_Funcionarios.txt_telefone.setText(tb_funcoionario.getModel().getValueAt(linha, 9).toString());
                 
    }//GEN-LAST:event_EditarActionPerformed
   }  
 }
    private void tb_funcoionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_funcoionarioMouseClicked
      FuncionariosDTO funcionariosDTO = new FuncionariosDTO();
        if (evt.getClickCount() == 2) {             
            if (tb_funcoionario.getSelectedRowCount() > 0) {
            int linha = tb_funcoionario.getSelectedRow();
            funcionariosDTO.setId_funcionario((int) tb_funcoionario.getValueAt(linha, 0));
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(null, "deseja mesmo alterar?");
            if (resposta == JOptionPane.YES_OPTION) {
                
         Alterar_Funcionarios alterar_Funcionarios = new Alterar_Funcionarios();
         alterar_Funcionarios.setSize(700, 500);
         alterar_Funcionarios.setVisible(true);
         Alterar_Funcionarios.txt_cod.setText(tb_funcoionario.getModel().getValueAt(linha, 0).toString());
         Alterar_Funcionarios.txt_nome.setText(tb_funcoionario.getModel().getValueAt(linha, 1).toString());
         Alterar_Funcionarios.txt_cpf.setText(tb_funcoionario.getModel().getValueAt(linha, 2).toString());
         Alterar_Funcionarios.txt_identidade.setText(tb_funcoionario.getModel().getValueAt(linha, 3).toString());
         Alterar_Funcionarios.txt_endereco.setText(tb_funcoionario.getModel().getValueAt(linha, 4).toString());
         Alterar_Funcionarios.txt_cep.setText(tb_funcoionario.getModel().getValueAt(linha, 5).toString());
         Alterar_Funcionarios.txt_numero.setText(tb_funcoionario.getModel().getValueAt(linha, 6).toString());
         Alterar_Funcionarios.txt_cidade.setText(tb_funcoionario.getModel().getValueAt(linha, 7).toString());
         Alterar_Funcionarios.txt_uf.setSelectedItem(tb_funcoionario.getModel().getValueAt(linha, 8).toString());
         Alterar_Funcionarios.txt_telefone.setText(tb_funcoionario.getModel().getValueAt(linha, 9).toString());
            }
            
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha!");

             }  
        }
    }//GEN-LAST:event_tb_funcoionarioMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Editar;
    private javax.swing.JMenuItem Excluir;
    private javax.swing.JPopupMenu Popuptb_funcionario;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable tb_funcoionario;
    public javax.swing.JFormattedTextField txt_cep;
    public javax.swing.JTextField txt_cidade;
    public javax.swing.JTextField txt_cod;
    public javax.swing.JFormattedTextField txt_cpf;
    public javax.swing.JTextField txt_endereco;
    public javax.swing.JTextField txt_identidade;
    public javax.swing.JTextField txt_nome;
    public javax.swing.JTextField txt_numero;
    public javax.swing.JFormattedTextField txt_telefone;
    public javax.swing.JComboBox<String> txt_uf;
    // End of variables declaration//GEN-END:variables
}
