/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import BLL.ClientesBLL;
import DTO.ClientesDTO;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casa
 */
public class Cadastro_Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro_Clientes
     */
    
    public Cadastro_Clientes() {
        initComponents();
        getRootPane().setDefaultButton(btn_cadastrar);
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        Excluir = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenuItem();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        radio_fisico = new javax.swing.JRadioButton();
        radio_juridico = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txt_empresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cnpj = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_endereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_celular = new javax.swing.JFormattedTextField();
        btn_cadastrar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cliente = new javax.swing.JTable();

        Excluir.setText("jMenuItem2");
        Excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExcluirMouseClicked(evt);
            }
        });
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jPopupMenu2.add(Excluir);

        Editar.setText("jMenuItem1");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPopupMenu2.add(Editar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("aSuperArts - Cadastro de Clientes");
        setToolTipText("");
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Código");

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        txt_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nome.setToolTipText("Digite seu nome");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Tipo");

        radio_fisico.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radio_fisico);
        radio_fisico.setText("Físico");
        radio_fisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_fisicoActionPerformed(evt);
            }
        });

        radio_juridico.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radio_juridico);
        radio_juridico.setText("Júridico");
        radio_juridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_juridicoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Empresa");

        txt_empresa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_empresa.setToolTipText("Digite o nome da empresa");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("CNPJ");

        txt_cnpj.setToolTipText("Digite o CNPJ");
        txt_cnpj.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("CPF");

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.setToolTipText("Digite seu CPF");
        txt_cpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("E-mail");

        txt_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_email.setToolTipText("Digite o E-mail");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Endereço");

        txt_endereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_endereco.setToolTipText("Digite seu Endereço");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Telefone");

        try {
            txt_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_telefone.setToolTipText("(xx)xxxx-xxxx");
        txt_telefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Celular");

        try {
            txt_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_celular.setToolTipText("(xx)xxxxx-xxxx");
        txt_celular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btn_cadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cadastrar)
                    .addComponent(jLabel7)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(radio_fisico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radio_juridico))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_empresa, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txt_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_celular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(txt_telefone, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel8)
                            .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_fisico)
                    .addComponent(radio_juridico)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cadastrar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6);

        jTabbedPane2.addTab("Cadastro", jPanel4);

        jPanel5.setLayout(new javax.swing.OverlayLayout(jPanel5));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tb_cliente.setAutoCreateRowSorter(true);
        tb_cliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Tipo", "Empresa", "CPF", "CNPJ", "E-mail", "Endereço", "Telefone", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_clienteMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_clienteMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_cliente);
        if (tb_cliente.getColumnModel().getColumnCount() > 0) {
            tb_cliente.getColumnModel().getColumn(0).setResizable(false);
            tb_cliente.getColumnModel().getColumn(1).setResizable(false);
            tb_cliente.getColumnModel().getColumn(2).setResizable(false);
            tb_cliente.getColumnModel().getColumn(3).setResizable(false);
            tb_cliente.getColumnModel().getColumn(4).setResizable(false);
            tb_cliente.getColumnModel().getColumn(5).setResizable(false);
            tb_cliente.getColumnModel().getColumn(6).setResizable(false);
            tb_cliente.getColumnModel().getColumn(7).setResizable(false);
            tb_cliente.getColumnModel().getColumn(8).setResizable(false);
            tb_cliente.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel1);

        jTabbedPane2.addTab("Editar", jPanel5);

        getContentPane().add(jTabbedPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void preencherTabela(){
        
        this.tb_cliente.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.tb_cliente.getColumnModel().getColumn(0).setMaxWidth(50);
        this.tb_cliente.getColumnModel().getColumn(0).setMinWidth(50);
        
        this.tb_cliente.getColumnModel().getColumn(1).setPreferredWidth(150);
        this.tb_cliente.getColumnModel().getColumn(1).setMaxWidth(150);
        this.tb_cliente.getColumnModel().getColumn(1).setMinWidth(150);
        
        this.tb_cliente.getColumnModel().getColumn(2).setPreferredWidth(70);
        this.tb_cliente.getColumnModel().getColumn(2).setMaxWidth(70);
        this.tb_cliente.getColumnModel().getColumn(2).setMinWidth(70);
        
        this.tb_cliente.getColumnModel().getColumn(3).setPreferredWidth(150);
        this.tb_cliente.getColumnModel().getColumn(3).setMaxWidth(150);
        this.tb_cliente.getColumnModel().getColumn(3).setMinWidth(150);
        
        this.tb_cliente.getColumnModel().getColumn(4).setPreferredWidth(150);
        this.tb_cliente.getColumnModel().getColumn(4).setMaxWidth(150);
        this.tb_cliente.getColumnModel().getColumn(4).setMinWidth(150);
        
        this.tb_cliente.getColumnModel().getColumn(5).setPreferredWidth(150);
        this.tb_cliente.getColumnModel().getColumn(5).setMaxWidth(150);
        this.tb_cliente.getColumnModel().getColumn(5).setMinWidth(150);
        
        this.tb_cliente.getColumnModel().getColumn(6).setPreferredWidth(200);
        this.tb_cliente.getColumnModel().getColumn(6).setMaxWidth(200);
        this.tb_cliente.getColumnModel().getColumn(6).setMinWidth(200);
        
        this.tb_cliente.getColumnModel().getColumn(7).setPreferredWidth(200);
        this.tb_cliente.getColumnModel().getColumn(7).setMaxWidth(200);
        this.tb_cliente.getColumnModel().getColumn(7).setMinWidth(200);
        
        ClientesBLL rg = new ClientesBLL();
        this.tb_cliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel modelo = (DefaultTableModel) tb_cliente.getModel();
        modelo.setNumRows(0);
        
        for(ClientesDTO cdto:rg.listarCliente()){
         modelo.addRow(new Object[]{
                cdto.getId_cliente(),
                cdto.getNome(),
                cdto.getTipo(),
                cdto.getEmpresa(),
                cdto.getCpf(),
                cdto.getCnpj(),
                cdto.getEmail(),
                cdto.getEndereco(),
                cdto.getTelefone(),
                cdto.getCelular()
            });
        }
    }
    private void tb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_clienteMouseClicked
       ClientesDTO clientesDTO = new ClientesDTO();
        if (evt.getClickCount() == 2) {             
            if (this.tb_cliente.getSelectedRowCount() > 0) {
            int linha = tb_cliente.getSelectedRow();
            clientesDTO.setId_cliente((int) this.tb_cliente.getValueAt(linha, 0));
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(null, "deseja mesmo alterar?");
            if (resposta == JOptionPane.YES_OPTION) {
                
                Alterar_Clientes alterar_Clientes = new Alterar_Clientes();
                alterar_Clientes.setSize(700, 500);
                alterar_Clientes.setVisible(true);
                Alterar_Clientes.txt_id_cliente.setText(tb_cliente.getModel().getValueAt(linha, 0).toString());
                Alterar_Clientes.txt_Nome.setText(tb_cliente.getModel().getValueAt(linha, 1).toString());
                Alterar_Clientes.radio_fisico.setText(tb_cliente.getModel().getValueAt(linha, 2).toString());
                Alterar_Clientes.txt_empresa.setText(tb_cliente.getModel().getValueAt(linha, 3).toString());
                Alterar_Clientes.txt_cpf.setText(tb_cliente.getModel().getValueAt(linha, 4).toString());
                Alterar_Clientes.txt_cnpj.setText(tb_cliente.getModel().getValueAt(linha, 5).toString());
                Alterar_Clientes.txt_email.setText(tb_cliente.getModel().getValueAt(linha, 6).toString());
                Alterar_Clientes.txt_endereco.setText(tb_cliente.getModel().getValueAt(linha, 7).toString());
                Alterar_Clientes.txt_telefone.setText(tb_cliente.getModel().getValueAt(linha, 8).toString());
                Alterar_Clientes.txt_celular.setText(tb_cliente.getModel().getValueAt(linha, 9).toString());
            }
            
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha!");

             }  
        }
    }//GEN-LAST:event_tb_clienteMouseClicked

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        ClientesBLL rg = new ClientesBLL();
        ClientesDTO clientesDTO = new ClientesDTO();
        
        clientesDTO.setNome(txt_nome.getText());
        clientesDTO.setCpf(txt_cpf.getText());
        clientesDTO.setEndereco(txt_endereco.getText());
        clientesDTO.setTelefone(txt_telefone.getText());
        clientesDTO.setCelular(txt_celular.getText());
        clientesDTO.setCnpj(txt_cnpj.getText());
        clientesDTO.setEmpresa(txt_empresa.getText());
        clientesDTO.setEmail(txt_email.getText());
        if(radio_fisico.isSelected()){
            clientesDTO.setTipo(radio_fisico.getActionCommand());
            
            //JOptionPane.showMessageDialog(null, radio_fisico.getActionCommand());
        }else{
            clientesDTO.setTipo(radio_juridico.getActionCommand());
            
            //JOptionPane.showMessageDialog(null, radio_juridico.getActionCommand());
        }
        rg.inserir(clientesDTO);
        JOptionPane.showMessageDialog(null, "Cliente cadastrado");
        preencherTabela();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void radio_fisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_fisicoActionPerformed
        if(radio_fisico.isSelected()){
            txt_empresa.setEnabled(false);
            txt_cnpj.setEnabled(false);
            txt_cnpj.setText("não contém");
            txt_empresa.setText("não contém");
        }
    }//GEN-LAST:event_radio_fisicoActionPerformed

    private void radio_juridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_juridicoActionPerformed
        if(radio_juridico.isSelected()){
            txt_cnpj.setEnabled(true);
            txt_empresa.setEnabled(true);
            txt_cnpj.setText("");
            txt_empresa.setText("");
        }
    }//GEN-LAST:event_radio_juridicoActionPerformed

    private void tb_clienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_clienteMouseReleased
        if(evt.isPopupTrigger()){
            jPopupMenu2.show(this, evt.getX(), 105);
            Excluir.setText("Excluir Cliente");
            Editar.setText("Editar Cliente");
            
        }
           
    }//GEN-LAST:event_tb_clienteMouseReleased

    private void ExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirMouseClicked
         
    }//GEN-LAST:event_ExcluirMouseClicked

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        ClientesDTO c = new ClientesDTO();
         ClientesBLL clienteBLL = new ClientesBLL();
        if (this.tb_cliente.getSelectedRowCount() > 0) {
            int linha = this.tb_cliente.getSelectedRow();
            c.setId_cliente((int) this.tb_cliente.getValueAt(linha, 0));
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir?");
            if (resposta == JOptionPane.YES_OPTION) {
                clienteBLL.ExcluirCliente(c);
                preencherTabela();
                JOptionPane.showMessageDialog(null, "Excluído!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        ClientesDTO clientesDTO = new ClientesDTO();
        ClientesBLL rg = new ClientesBLL();
        if (this.tb_cliente.getSelectedRowCount() > 0) {
            int linha = tb_cliente.getSelectedRow();
            clientesDTO.setId_cliente((int) this.tb_cliente.getValueAt(linha, 0));
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(null, "Deseja mesmo editar?");
            if (resposta == JOptionPane.YES_OPTION) {
                
                Alterar_Clientes alterar_Clientes = new Alterar_Clientes();
                alterar_Clientes.setSize(700, 500);
                alterar_Clientes.setVisible(true);
                Alterar_Clientes.txt_id_cliente.setText(tb_cliente.getModel().getValueAt(linha, 0).toString());
                Alterar_Clientes.txt_Nome.setText(tb_cliente.getModel().getValueAt(linha, 1).toString());
                Alterar_Clientes.radio_fisico.setText(tb_cliente.getModel().getValueAt(linha, 2).toString());
                Alterar_Clientes.txt_empresa.setText(tb_cliente.getModel().getValueAt(linha, 3).toString());
                Alterar_Clientes.txt_cpf.setText(tb_cliente.getModel().getValueAt(linha, 4).toString());
                Alterar_Clientes.txt_cnpj.setText(tb_cliente.getModel().getValueAt(linha, 5).toString());
                Alterar_Clientes.txt_email.setText(tb_cliente.getModel().getValueAt(linha, 6).toString());
                Alterar_Clientes.txt_endereco.setText(tb_cliente.getModel().getValueAt(linha, 7).toString());
                Alterar_Clientes.txt_telefone.setText(tb_cliente.getModel().getValueAt(linha, 8).toString());
                Alterar_Clientes.txt_celular.setText(tb_cliente.getModel().getValueAt(linha, 9).toString());
            }
            
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha!");

             }  
    }//GEN-LAST:event_EditarActionPerformed
    public void validarCampos(){
        if(txt_nome.getText().equals("")){
            txt_nome.grabFocus();
        }
        if(txt_cpf.getText().equals(" . . - ")){
            txt_cpf.grabFocus();
        }
        if(txt_endereco.getText().equals("")){
            txt_endereco.grabFocus();
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Editar;
    private javax.swing.JMenuItem Excluir;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton radio_fisico;
    private javax.swing.JRadioButton radio_juridico;
    public static javax.swing.JTable tb_cliente;
    private javax.swing.JFormattedTextField txt_celular;
    private javax.swing.JFormattedTextField txt_cnpj;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_empresa;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JFormattedTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
